// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/console-patient-layouts/Cockpit.tsx": () => import("../components/mockups/console-patient-layouts/Cockpit.tsx"),
  "./components/mockups/console-patient-layouts/Dossier.tsx": () => import("../components/mockups/console-patient-layouts/Dossier.tsx"),
  "./components/mockups/console-patient-layouts/Sidebar.tsx": () => import("../components/mockups/console-patient-layouts/Sidebar.tsx")
};
